### PR TITLE
Esnook 74 parking information

### PR DESCRIPTION
**Pull request by zegameiro**
Improved Navigation drawer a lot.
Home screen is now the map one.
When log in with success, the user is redirected to the home screen instead of the profile one.

image

### CODE REVIEW

**Review by WildBunnie — APPROVED** [review]
The ui looks great :+1:

**Review by fungame2270 — APPROVED** [review]
the ui lookus greato

**Review by WildBunnie — APPROVED** [review]
i love github

**Review by fungame2270 — APPROVED** [review]
Indeed

**Review by Dan1m4D — APPROVED** [review]
Everything looks great! Good job!

**Review by WildBunnie — APPROVED** [review]
does it work now?

**Pull request merged**
