### PR TITLE
Esnook 74 parking information

### PR DESCRIPTION
**Pull request by zegameiro**
Fixed navigation, it wasn't possible to interact with the screens only the drawer and now its possible and now the drawer button is in an top app bar

### CODE REVIEW

**Review by Dan1m4D — CHANGES_REQUESTED** [review]
I don't know how but i can't log in on the app through Google IdP. I've noticed you changed the google import to the lib notation on the gradle file.

Can you fix the login so I can see your changes? Thxxx

**Review by fungame2270 — APPROVED** [review]
lgtm

**Comment by zegameiro** [comment]
> Can you fix the log

You need to provide me you're SHA-1 key, and to obtain this you can follow the tutorial in this [link](https://stackoverflow.com/questions/27609442/how-to-get-the-sha-1-fingerprint-certificate-in-android-studio-for-debug-mode)

**Review by Dan1m4D — APPROVED** [review]

**Comment by Dan1m4D** [comment]
I reviewed your changes and they look pretty good. The interactions work as expected. Good job!!!

**Pull request merged**
